---
- name: remove simlink default
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify:
    - reload_nginx

- name: creating vhost dir
  file:
    path: "{{ item.dir_path }}"
    state: directory
  loop:
    - {dir_path: "/var/www/doc"}
  notify:
    - reload_nginx

- name: copy files to vhost
  copy:
    src: "doc/"
    dest: "/var/www/doc/"
    mode: 644      

- name: creating vhost conf file
  template:
    src: "{{ item.src_file }}"
    dest: "{{ item.dest_file }}"
  loop:
    - {
      src_file: "vhost.conf.j2",
      dest_file: "/etc/nginx/sites-available/doc.conf",
      vh_name: "doc",
      vh_port: 8080,
    }
  notify:
    - reload_nginx

- name: linking vhost conf file
  file:
    src: "{{ item.src_file }}"
    dest: "{{ item.dest_file }}"
    state: link
  loop:
    - {
      src_file: "/etc/nginx/sites-available/doc.conf",
      dest_file: "/etc/nginx/sites-enabled/doc.conf",
    }
  notify:
    - reload_nginx
